[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'micchy326/gtags.vim'

[[plugins]]
repo = 'micchy326/gtags-cscope.vim'

[[plugins]]
repo = 'will133/vim-dirdiff'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'micchy326/vim-coloresque'
merged = 0

[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'm-pilia/vim-ccls'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'CoatiSoftware/vim-sourcetrail'

[[plugins]]
repo = 'kamykn/spelunker.vim'

[[plugins]]
repo = 'greymd/oscyank.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'

#[[plugins]]
#repo = 'lambdalisue/fern-git-status.vim'
#merged = 0
 
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'liuchengxu/vista.vim'
