[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'micchy326/gtags.vim'

[[plugins]]
repo = 'micchy326/gtags-cscope.vim'

[[plugins]]
repo = 'micchy326/vim-dirdiff'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Rip-Rip/clang_complete'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'


